env = Environment(CPPFLAGS=['-Wall','-g'])
env.ParseConfig('pkg-config --cflags --libs glib-2.0')
env.Append(CPPPATH = ['/home/dov/github/fribidi/lib/',
                      '/home/dov/github/fribidi/charset/'],
           LIBPATH = '/home/dov/github/fribidi/lib/.libs',
           LIBS=['fribidi'])
env.Program('test',
            ['test.c'],
            )
